### PR TITLE
Pre commit packages update

### PR DESCRIPTION
**Pull request by MaevaBrunelles**

### CODE REVIEW

**Comment by MaevaBrunelles** [comment]
@justinmayer : it seems that `pre-commit` CI is conflicting with `Lint` CI.

As you can see in this PR, I tried to update packages version raised by `pre-commit`bot in #38.
My initial commit https://github.com/pelican-plugins/seo/pull/40/commits/b6a6a84782eacc5c757b2fe70d575757ea830ea8 failed only on `pre-commit` check.
So `pre-commit` automatically commits a fix: https://github.com/pelican-plugins/seo/pull/40/commits/1dc31a3eca55d71089e3ce5d2244e84c630b09c5
Thus now `pre-commit` check is successful but no more `build / Lint` checks. The changement introduced by `pre-commit` bot conflicts with linting rules. 

I guess there is an issue on the `pre-commit` configuration on Actions side, but it seems I don't have rights to look deeper.

**Comment by justinmayer** [comment]
> it seems that `pre-commit` CI is conflicting with `Lint` CI.

I'm still new to Pre-commit CI, so I don't yet fully understand how and why it does the things it does. In this case, it seems to have made some needed changes but not others. The failure message in GitHub Actions was related to  import order.

> I guess there is an issue on the `pre-commit` configuration on Actions side, but it seems I don't have rights to look deeper.

Perhaps I misunderstand GitHub's permissions system… Are you not able to see the linter failure detail here? https://github.com/pelican-plugins/seo/runs/2605224317?check_suite_focus=true#step:8:10

As far as resolving this… Rather than sort things out within the context of this PR, it was easier for me to create a new branch and make the appropriate changes: https://github.com/pelican-plugins/seo/pull/42

Would you please have a look there and let me know whether everything looks okay to you?

**Comment by MaevaBrunelles** [comment]
> The failure message in GitHub Actions was related to import order.

Yes, while `pre-commit` command returns no errors when I ran it on local, before pushing. That's the issue. I'm wondering why `isort` on local doesn't have order import errors, while it does on `pre-commit-ci`.

> Are you not able to see the linter failure detail here?

Yes I am. But I would like to see the configuration of GitHub Actions, to see how `pre-commit-ci` run `isort`, with which parameters. Same goes for GitHub Actions, I can see run but not the actual code of the steps.

It seems that your commit https://github.com/pelican-plugins/seo/pull/42/commits/ef3874e00f53d7b9d870eb857170ba5b742ee948 fixes the issue as the CI is green, but IMHO, it's a cheat, not a fix. `seo` should be part of `FIRSTPARTY`. Declaring `seo` as a section apart pleases `isort` (on CI) because it's normal to have line return between two sections. Indeed this solution fixes https://github.com/pelican-plugins/seo/pull/43/commits/1787f67c2dd5cc8a2a5e649f285fae6a7cf8bde4, but I'm not sure it's the solution. 

To be sure of the root cause, I think I need to see the GitHub Actions configuration. 

Would you mind giving me this permission to dig?

**Comment by justinmayer** [comment]
It's not a GitHub permissions issue. The CI configuration is totally public and visible: https://github.com/pelican-plugins/seo/blob/master/.github/workflows/main.yml

**Comment by MaevaBrunelles** [comment]
I failed to find the root cause of this issue, and coming back from vacations isn't helping, so I've merged #42. I'll try to dig another time!

Many thanks for your time and your PR which fix the issue :)

**Pull request closed without merging**
