### PR TITLE
Fix schemas generated in wrong script tags

### PR DESCRIPTION
**Pull request by MaevaBrunelles**

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Maëva. You might want to wait before adding (another) `RELEASE.md` file. I think there is a [dependency-related issue](https://github.com/pelican-plugins/seo/runs/1346375326?check_suite_focus=true#step:4:105) that needs resolving in AutoPub first. Will advise when I have more info.

**Comment by MaevaBrunelles** [comment]
Oh this is why #20 didn't trigger the new release. I prefered revert the PR and add the `RELEASE.md` in a separated PR just to be sure.

**Comment by MaevaBrunelles** [comment]
But I guess it's maybe worth to decline this PR, revert the #21, and have the release done with #20 (if it's still possible) when the issue will be fixed.

**Comment by justinmayer** [comment]
Since there are no "take-backs" (i.e., once a release is published to PyPI, that version cannot be reverted), I think the best thing to do is to wait until you are sure everything is fixed properly. Once everything in `master` is tested and functioning well, then the release can be made. _Where_ that happens, in terms of which PR it is included in, is not particularly important. 😊

**Comment by justinmayer** [comment]
@MaevaBrunelles: I just released [AutoPub 0.1.7](https://github.com/autopub/autopub/releases/tag/0.1.7) with a less-restrictive dependency specification for TOMLkit, which should resolve the problem encountered during the last deployment run. I also switched the relevant installation command to try [using Pip's new dependency resolver](https://github.com/pelican-plugins/seo/commit/17e9af8d1b31032fca05d5b4ce75d68a356aae42), which will become the default when Pip 20.3 is released. This way we can find out ahead of time whether there are any problems with this particular install step. To that end, I recommend rebasing this PR on current master before merging.

Also, as you can see in this PR, there seems to be a linting failure, presumably because `invoke black` was not run before the commit was pushed. Do you have Pre-commit installed and configured? If not, try running `invoke setup` in order to ensure that Pre-commit and its hooks have been installed, which in the future should catch these problems during your local `git commit` invocation, _before_ the non-conforming code gets pushed and flagged by CI. 😉

**Comment by MaevaBrunelles** [comment]
@justinmayer Got it, I've run `invoke setup` and it works nicely. The `1.0.2` is now released. I'll follow your recommandation and create a dedicated PR for the future `RELEASE.md`. Thanks again for all your explanations!

**Pull request merged**
