### PR TITLE
Convert to namespace plugin format

### PR DESCRIPTION
**Pull request by justinmayer**
Adjusting the filesystem layout to the new namespace plugin format allows plugins to be Pip-installed without needing to manually enable plugins in the Pelican settings file.

This also renames the plugin to be "SEO", both for simplicity as well as to implicitly indicate that we don't intend to have multiple SEO-related plugins floating about. 😄

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi @MaevaBrunelles! Please accept my apologies for the delay in creating the new repository. As you can see, all your commits to master are present here, and so far nothing in master has been touched or changed. I took the liberty of submitting this pull request with the above-mentioned changes. Obviously, tweaking the name to “SEO” is totally optional and subject to your approval. I just thought it would be simpler and cleaner that way.

After converting to the new format, I was able to Pip-install this plugin, and everything behaved as expected. The report produced by the plugin is quite helpful, and I’m excited to run it periodically on my own sites and heed the report’s suggestions. :grin:

I haven’t touched the README file yet because I wanted you to review the changes in this PR first. Assuming you approve, we can merge this and then I’ll continue making a few tweaks to the README file. Thanks again for the terrific work on this plugin! 💯

**Comment by MaevaBrunelles** [comment]
Hello @justinmayer,

Many thanks for the repository creation! I'm very glad to hear that this plugin is helpful for your sites, I hope it'll be too for many other :D My goal is to improve these basis features according to users feedback.

I see no trouble in the fact of renaming the plugin "SEO", it goes straight to the point and it makes sense to try to have a referent plugin in this specific domain.

About this PR, I'm afraid that you didn't see my branch where I pushed the new plugin template based on your CookieCutter: https://github.com/MaevaBrunelles/pelican-seo/tree/update-project-organization-to-cookiecutter-template I should have link it when I asked for the repository creation on IRC, apologies.
This branch contains all the files generated by CookieCutter, a bugfix on a test, and I just pushed a new commit eb0e784dc96c309d695d62548d67c58083623044 which include your changes (rename the repo). I took the opportunity to rename my own repository to be more consistant. I let you check, if you can of course, the modifications to be sure everything is good.

If it's relevant to you too, I suggest to decline this PR and create a new one based on the cookiecutter branch.

**Comment by justinmayer** [comment]
Hi @MaevaBrunelles. Thank you for pointing that out. Rather than close this PR and create another one, I chose instead to re-use this PR and replace its contents with the changes from your `update-project-organization-to-cookiecutter-template` branch. I took the liberty of making a few tweaks, all of which were minor enough to include in a single "miscellaneous" commit instead of separate discrete commits.

Please let me know if you have any questions about the changes I made. Otherwise, please feel free to merge this PR. I am excited to be working with you on this, as I am sure I will learn a lot from the collaboration! 😁

**Comment by justinmayer** [comment]
By the way, yesterday I sent you an invitation via GitHub to join this repository as a Maintainer, but it seems you have not accepted it yet. Did you receive the invitation? The current status shows:

> Pending Invite ... Awaiting MaevaBrunelles’s response

Perhaps you can check here to see the invitation and accept it: https://github.com/notifications

**Comment by MaevaBrunelles** [comment]
I just forgot to accept, it's now done. Everything seems ok to me, so let's merge!

**Pull request merged**
