### PR TITLE
Let's launch a new release

### PR DESCRIPTION
**Pull request by MaevaBrunelles**

### CODE REVIEW

**Comment by MaevaBrunelles** [comment]
@justinmayer: accordingly with what you explained [here](https://github.com/pelican-plugins/seo/issues/8#issuecomment-703483258), I've created a `RELEASE.md` to release a new version of the plugin, including all the modifications since the first release. I know it's a bad way of doing because it's not linked to a specific PR, which can make it difficult for you to make sure everything is working properly.

**Comment by justinmayer** [comment]
Via 8e4f8b7, I reverted the version number in `pyproject.toml` back to the current actual `1.0.0` release version. This will ensure that when the `RELEASE.md` file is merged, the version number will automatically be incremented properly to `1.0.1`. [I mentioned this previously](https://github.com/pelican-plugins/seo/pull/10#discussion_r499424810), and since I realized the version number hadn’t been fixed yet, I went ahead and took care of that.

I know that the release process for most other projects involves manually changing version numbers, but once you get used to never touching version numbers and instead letting AutoPub do that for you, you will probably find that you rather enjoy not having to mess with manual version number incrementing. 😁

**Review by justinmayer — APPROVED** [review]
Everything here looks good to me. I think this can be merged and thus a new release issued. 🎉

**Comment by MaevaBrunelles** [comment]
Oh my apologies for this. I thought I had already decremented the number version in a previous commit, and looking at the PR history, I find this commit https://github.com/pelican-plugins/seo/pull/11/commits/17ece905be4ef21774d45a7146ec9bf1667f04ed... which effectively decrement the number version, but obviously not sufficiently. 

I've no doubt I'll enjoy this process once I get used to it 👍 

Thanks for your quick feedback !

**Pull request merged**
